homeassistant:
  # Name of the location where Home Assistant is running
  name: Beach House
  # Location required to calculate the time the sun rises and sets
  latitude: 36.965667
  longitude: -121.963298
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 11
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
    
group:
  back_fifty:
    - switch.smart_plug
  big_house:
    - switch.coffee 
    
  People:
    - device_tracker.16da431977ef
    - device_tracker.16da431977f0
    - device_tracker.appletv2    
    - device_tracker.ec1a597b5d6d    
    - device_tracker.ec1a59f83bf9
    - device_tracker.homepi
    - device_tracker.ipad
    - device_tracker.ipad_2    
    - device_tracker.jj
    - device_tracker.jjsiphone
    - device_tracker.johnsmbp3
    - device_tracker.johnsmbp3_2
    - device_tracker.roku_2_xd__841
    - device_tracker.roku_stick__387
    - device_tracker.vmb3010
    
  Weather:
    - sensor.dark_sky_daily_summary
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_nearest_storm_distance
    - sensor.pws_location
    - sensor.pws_wind_dir
    - sensor.pws_wind_gust_mph
    - sensor.pws_wind_mph
    
  Network:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping
    
# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

http:
  api_password: !secret http_api_password
  ssl_certificate: /etc/keys/fullchain.pem
  ssl_key: /etc/keys/privkey.pem


# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  
      # Uncomment this if you are using SSL or running in Docker etc
  #  base_url: opalcliff.duckdns.org:8123




automation:
  alias: Turn on light an hour before sun sets
  trigger:
    platform: sun
    event: sunset
    offset: "-00:31:00"
  condition:
    condition: state
    entity_id: device_tracker.jjsiphone
    state: 'home'
  action:
    service: switch.turn_on
    entity_id: group.back_fifty

automation 2:
  alias: Turn off back fify lights late at night
  trigger:
    platform: time
    after: '23:15:00'
  action:
    service: switch.turn_off
    entity_id: group.back_fifty

#mqtt:
 # broker: m12.cloudmqtt.com
  #port: 13031
  #username: evnmiodp
  #password: !secret mqtt_password

device_tracker:
  - platform: netgear
    host: 10.0.0.1
    username: admin
    password: !secret device_tracker_password
    interval_seconds: 10
    consider_home: 180
    track_new_devices: yes

  - platform: owntracks
  
wemo:


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
# sensor:
#  platform: yr

# Text to speech
tts:
  platform: google

sensor:
# Weather Data
  - platform: darksky
    api_key: !secret dark_sky_api
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - precip_probability
      - temperature
      - visibility
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min

  - platform: wunderground
    api_key: !secret wunderground_api
    pws_id: 'KCACAPIT5'
    monitored_conditions:
      - alerts
      - location
      - observation_time
      - precip_today_in
      - precip_today_string
   #   - station_id: 'KCASANTA290'
      - temperature_string
      - temp_f
      - visibility_mi
      - weather
      - wind_dir
      - wind_gust_mph
      - wind_mph
      
# system     
  
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
      
